apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: app-service
          image: app-service:1.0
          imagePullPolicy: IfNotPresent
          #Makes Kubernetes wait 5 seconds before sending the SIGTERM signal to the Pod by that Kubernetes will update its components to not to send new requests to the pod.( sleep is to avoid race condition)
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5"]
          ports:
            - containerPort: 8080
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            
            - name: SPRING_DATA_REDIS_HOST
              value: my-redis
            
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            
            - name: OAUTH2_SERVICE_ISSUER-URI
              value: http://auth-service
            
            - name: INVOICE_SERVICE_URI
              value: http://invoice-service
            
            - name: PAYMENT_SERVICE_URI
              value: http://payment-service
            
            - name: SPRING_PROFILES_ACTIVE
              value: proddata

            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK
              value: debug
